Fdawgs/node-poppler

src/index.js, src/index.test.js
=> Add pdfDetach function

package.json, src/index.js, src/index.test.js
=> Add pdfSeparate function

API.md, src/index.js, src/index.test.js
=> Add pdfFonts function

API.md, package.json, src/index.js, src/index.test.js
=> Add pdfUnite function

.travis.yml, API.md, src/index.js, src/index.test.js, test_docs/test.txt
=> Add pdfAttach function

src/index.js, src/index.test.js
=> Add pdfImages function

.travis.yml, package.json
=> chore: reduce minimum nodejs engine version from 12.x to 10.x

package.json, src/index.js, yarn.lock
=> refactor(index): replace execa dependency with native execfile function

package.json
This reverts commit 011f5d2e494c38b9862b63b0b375eafc2d7cae1f.
=> Revert "build(deps-dev): bump husky from 4.3.8 to 5.0.9 (#198)"

src/index.js, src/index.test.js
=> feat: support buffer input for functions

API.md, package.json, src/index.d.ts, src/index.js, src/index.test.js
=> feat(index): add `printAsJson` arg to `pdfInfo()` options

package.json, src/index.js, src/index.test.js
=> fix(index): normalize binary paths

API.md, src/index.d.ts, src/index.js, src/index.test.js
=> fix(index): pdftocairo output encoding

src/index.js, src/index.test.js
=> fix(index): correct message thrown for missing binaries

.github/workflows/ci.yml, package.json
BREAKING CHANGE: drop support for EOL node 12
=> chore!: drop support for node 12

scripts/license-checker.js, src/index.js
Same style as node docs for functions
=> chore: use nouns for leading word in function description tags

API.md, src/index.js, types/index.d.ts
See https://github.com/jsdoc/jsdoc/issues/1197
=> fix(index): return types don't support promise rejection values

.eslintrc.js, .github/workflows/ci.yml, package.json, tsconfig.json
BREAKING CHANGE: dropped support for EOL node 14 and 16
=> chore!: drop support for node 14 and 16

README.md
=> docs(readme): add parameter for `pdfToText` function

.npmrc, package.json
=> chore(.npmrc): enforce strict engine checks

.github/workflows/automerge.yml, README.md, package.json, scripts/license-checker.js, src/index.js, src/index.test.js
=> build(deps): remove upath

.eslintrc.js, src/index.js
=> perf(index): optimise `parseOptions`

.github/workflows/ci.yml, README.md, package.json
=> chore(package): standardise test script naming

src/index.js
=> perf(index): destruct push in `pdfUnite`; replace `forEach` in `pdfInfo`

src/index.js
=> refactor(index): stop rethrowing errors

LICENSE
=> chore(license): replace date range with `-present`

src/index.js
=> style(index): use upper snakecase for cached values

src/index.test.js
=> test(index): build test directory in cleaner fashion

src/index.test.js
=> test(index): use posix for globbing

src/index.js
=> refactor(index): stop rethrowing errors in `pdfToCairo()`

.github/workflows/ci.yml, package.json
=> ci(ci): add typecheck to lint job

API.md, src/index.js, src/index.test.js
=> chore(index): add throw jsdoc tags; add type guards to tests
